#!/usr/bin/env node

/**
 * Utopia Design System — Token Generator
 *
 * Usage:
 *   node generate-tokens.mjs <config.json>
 *   node generate-tokens.mjs --config '{"minWidth":320,"maxWidth":1440,...}'
 *   node generate-tokens.mjs                           # interactive mode
 *
 * Config structure and defaults:
 *   {
 *     "type": {              // optional — type scale config
 *       "minWidth": 375,
 *       "maxWidth": 1440,
 *       "minFontSize": 16,
 *       "maxFontSize": 20,
 *       "minTypeScale": 1.2,
 *       "maxTypeScale": 1.333,
 *       "negativeSteps": 2,
 *       "positiveSteps": 5,
 *       "relativeTo": "viewport-width",
 *       "labelStyle": "utopia"
 *     },
 *     "space": {             // optional — space scale config
 *       "minWidth": 375,
 *       "maxWidth": 1440,
 *       "minSize": 8,
 *       "maxSize": 12,
 *       "positiveSteps": [0.5, 1, 1.5, 2, 3, 4, 6],
 *       "negativeSteps": [0.25],
 *       "relativeTo": "viewport-width",
 *       "customSizes": ["xs-l"]
 *     },
 *     "format": "css"        // "css" | "tailwind" | "scss" | "json"
 *   }
 */

import { readFileSync } from 'fs';
import { calculateTypeScale, calculateSpaceScale, calculateClamps } from './calculate.mjs';

// ─── Scale name resolver ─────────────────────────────────────────────────────

const SCALES = JSON.parse(readFileSync(new URL('./scales.json', import.meta.url), 'utf-8'));

/**
 * Resolve a scale name or numeric value to a number.
 * @param {string|number} input  — e.g. "perfect-fourth", 1.333
 * @returns {number}
 */
export function resolveScale(input) {
  if (typeof input === 'number') return input;
  if (typeof input === 'string') {
    const numeric = parseFloat(input);
    if (!isNaN(numeric)) return numeric;
    const entry = SCALES[input.toLowerCase().replace(/\s+/g, '-')];
    if (entry && entry.value !== null) return entry.value;
  }
  throw new Error(`Unknown scale: "${input}". Use a numeric value or one of: ${Object.keys(SCALES).join(', ')}`);
}

// ─── Formatters ──────────────────────────────────────────────────────────────

function formatCSS(typeSteps, spaceScale, clamps) {
  const lines = [':root {'];

  if (typeSteps && typeSteps.length) {
    lines.push('  /* ─── Fluid Type Scale ─── */');
    for (const s of typeSteps) {
      const label = `--font-size-${s.label}`;
      lines.push(`  ${label}: ${s.clamp};`);
    }
  }

  if (spaceScale && spaceScale.sizes.length) {
    lines.push('');
    lines.push('  /* ─── Fluid Space Scale ─── */');
    for (const size of spaceScale.sizes) {
      lines.push(`  --space-${size.label}: ${size.clamp};`);
    }
  }

  if (spaceScale && spaceScale.oneUpPairs.length) {
    lines.push('');
    lines.push('  /* ─── One-Up Pairs ─── */');
    for (const pair of spaceScale.oneUpPairs) {
      lines.push(`  --space-${pair.label}: ${pair.clamp};`);
    }
  }

  if (spaceScale && spaceScale.customPairs.length) {
    lines.push('');
    lines.push('  /* ─── Custom Pairs ─── */');
    for (const pair of spaceScale.customPairs) {
      lines.push(`  --space-${pair.label}: ${pair.clamp};`);
    }
  }

  if (clamps && clamps.length) {
    lines.push('');
    lines.push('  /* ─── Custom Clamps ─── */');
    for (const c of clamps) {
      lines.push(`  --clamp-${c.label}: ${c.clamp};`);
    }
  }

  lines.push('}');
  return lines.join('\n');
}

function formatTailwind(typeSteps, spaceScale, clamps) {
  const lines = [
    '/** @type {import("tailwindcss").Config} */',
    'module.exports = {',
    '  theme: {',
    '    extend: {'
  ];

  if (typeSteps && typeSteps.length) {
    lines.push('      // ─── Fluid Font Sizes ───');
    lines.push('      fontSize: {');
    for (const s of typeSteps) {
      lines.push(`        '${s.label}': '${s.clamp}',`);
    }
    lines.push('      },');
  }

  if (spaceScale && spaceScale.sizes.length) {
    lines.push('      // ─── Fluid Spacing ───');
    lines.push('      spacing: {');
    for (const size of spaceScale.sizes) {
      lines.push(`        '${size.label}': '${size.clamp}',`);
    }
    for (const pair of spaceScale.oneUpPairs) {
      lines.push(`        '${pair.label}': '${pair.clamp}',`);
    }
    for (const pair of spaceScale.customPairs) {
      lines.push(`        '${pair.label}': '${pair.clamp}',`);
    }
    lines.push('      },');
  }

  lines.push('    }');
  lines.push('  }');
  lines.push('};');
  return lines.join('\n');
}

function formatSCSS(typeSteps, spaceScale, clamps) {
  const lines = [
    '// ─── Fluid Design System ───',
    '// Auto-generated by utopia-design-system',
    '',
    '// =========================================',
    '// Type Scale',
    '// =========================================',
    ''
  ];

  if (typeSteps && typeSteps.length) {
    for (const s of typeSteps) {
      lines.push(`$font-size-${s.label}: ${s.clamp};`);
    }
  }

  if (spaceScale && spaceScale.sizes.length) {
    lines.push('');
    lines.push('// =========================================');
    lines.push('// Space Scale');
    lines.push('// =========================================');
    lines.push('');
    for (const size of spaceScale.sizes) {
      lines.push(`$space-${size.label}: ${size.clamp};`);
    }
    for (const pair of spaceScale.oneUpPairs) {
      lines.push(`$space-${pair.label}: ${pair.clamp};`);
    }
    for (const pair of spaceScale.customPairs) {
      lines.push(`$space-${pair.label}: ${pair.clamp};`);
    }
  }

  if (clamps && clamps.length) {
    lines.push('');
    lines.push('// =========================================');
    lines.push('// Custom Clamps');
    lines.push('// =========================================');
    lines.push('');
    for (const c of clamps) {
      lines.push(`$clamp-${c.label}: ${c.clamp};`);
    }
  }

  return lines.join('\n');
}

/**
 * Format tokens as serialisable data (useful for further processing).
 */
function formatJSON(typeSteps, spaceScale, clamps) {
  return JSON.stringify({ typeSteps, spaceScale, clamps }, null, 2);
}

// ─── Interactive Prompts ─────────────────────────────────────────────────────

async function interact() {
  const { createInterface } = await import('readline');
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  const ask = (q) => new Promise(r => rl.question(q, r));

  console.log('\n  Utopia Design System Generator\n');

  const scaleNames = Object.entries(SCALES).filter(([k, v]) => v.value !== null);
  console.log('Available scales:');
  for (const [k, v] of scaleNames) {
    console.log(`  ${k.padEnd(20)} ${v.value}  — ${v.description}`);
  }
  console.log();

  const rawScale = await ask('Type scale (e.g. "perfect-fourth" or a number like 1.333): ');
  const singleScale = await ask('Use same scale for min/max? (Y/n): ');
  const typeScaleValue = resolveScale(rawScale.trim());
  let maxTypeScale = typeScaleValue;

  if (singleScale.toLowerCase().startsWith('n')) {
    const rawMax = await ask('Max viewport type scale: ');
    maxTypeScale = resolveScale(rawMax.trim());
  }

  const minW = parseFloat(await ask('Min viewport width (px) [375]: ') || '375');
  const maxW = parseFloat(await ask('Max viewport width (px) [1440]: ') || '1440');
  const minFS = parseFloat(await ask('Min font size (px) [16]: ') || '16');
  const maxFS = parseFloat(await ask('Max font size (px) [20]: ') || '20');
  const neg = parseInt(await ask('Negative type steps [2]: ') || '2');
  const pos = parseInt(await ask('Positive type steps [5]: ') || '5');

  const doSpace = (await ask('Generate space scale too? (Y/n): ') || 'y').toLowerCase();
  let spaceConfig = null;

  if (doSpace.startsWith('y')) {
    const spaceMin = parseFloat(await ask('Space base min (px) [8]: ') || '8');
    const spaceMax = parseFloat(await ask('Space base max (px) [12]: ') || '12');
    spaceConfig = {
      minWidth: minW, maxWidth: maxW,
      minSize: spaceMin, maxSize: spaceMax,
      positiveSteps: [0.5, 1, 1.5, 2, 3, 4, 6],
      negativeSteps: [0.25],
      relativeTo: 'viewport-width'
    };
  }

  const format = (await ask('Output format (css/tailwind/scss/json) [css]: ') || 'css').toLowerCase();

  rl.close();

  return {
    type: {
      minWidth: minW, maxWidth: maxW,
      minFontSize: minFS, maxFontSize: maxFS,
      minTypeScale: typeScaleValue, maxTypeScale,
      negativeSteps: neg, positiveSteps: pos,
      relativeTo: 'viewport-width', labelStyle: 'utopia'
    },
    space: spaceConfig,
    format
  };
}

// ─── Main ────────────────────────────────────────────────────────────────────

async function main() {
  let config;

  if (process.argv[2]) {
    const arg = process.argv[2];
    if (arg.startsWith('{')) {
      config = JSON.parse(arg);
    } else if (arg.startsWith('--config=')) {
      config = JSON.parse(arg.slice(9));
    } else {
      config = JSON.parse(readFileSync(arg, 'utf-8'));
    }
  } else {
    config = await interact();
  }

  // Resolve scale names if strings
  if (config.type) {
    config.type.minTypeScale = resolveScale(config.type.minTypeScale ?? config.type.minTypeScale);
    config.type.maxTypeScale = resolveScale(config.type.maxTypeScale ?? config.type.maxTypeScale);
  }

  // Calculate everything
  const typeSteps = config.type ? calculateTypeScale(config.type) : null;
  const spaceScale = config.space ? calculateSpaceScale(config.space) : null;
  const customClamps = config.clamps
    ? calculateClamps({ ...config.clamps, pairs: config.clamps.pairs })
    : null;

  // Format output
  const format = config.format || 'css';
  let output;
  switch (format) {
    case 'tailwind': output = formatTailwind(typeSteps, spaceScale, customClamps); break;
    case 'scss':     output = formatSCSS(typeSteps, spaceScale, customClamps);     break;
    case 'json':     output = formatJSON(typeSteps, spaceScale, customClamps);     break;
    default:         output = formatCSS(typeSteps, spaceScale, customClamps);       break;
  }

  process.stdout.write(output + '\n');
}

main().catch(err => {
  console.error('Error:', err.message);
  process.exit(1);
});
